### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by LoreImbo** [Yung-Jer/Local-Statistics-for-Generative-Image-Detection#1]
Very interesting and nice work!
Do you have plans to release the code?
Thank you

**Comment by Yung-Jer** [comment]
Hi Lorelmbo, thank you for you message for me. However, unfortunately, my team decided to release the code only after it is accepted by a conference.

**Comment by LoreImbo** [comment]
Hi, thank you for your reply.
I fully understand, do you happen to know the possible acceptance date of the article yet?

**Comment by Yung-Jer** [comment]
Hi, if this paper is accepted, the code will be updated after the end of February 2024.
